// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package slacklogger.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import slacklogger.implementation.SlackMessageSender;

public class SendMessageToSlack extends CustomJavaAction<java.lang.String>
{
	private java.lang.String token;
	private java.lang.String channel;
	private java.lang.String message;

	public SendMessageToSlack(IContext context, java.lang.String token, java.lang.String channel, java.lang.String message)
	{
		super(context);
		this.token = token;
		this.channel = channel;
		this.message = message;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String result = new SlackMessageSender().sendMessage(token, channel, message);
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SendMessageToSlack";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
