// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package slacklogger.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the SlackLogger module
	public static void aCT_ReConfigRequest(IContext context, slacklogger.proxies.SlackLoggerStatus _slackLoggerStatus)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SlackLoggerStatus", _slackLoggerStatus == null ? null : _slackLoggerStatus.getMendixObject());
		Core.microflowCall("SlackLogger.ACT_ReConfigRequest").withParams(params).execute(context);
	}
	public static void aCT_SendTestMessage(IContext context, slacklogger.proxies.SlackLoggerConfig _slackLoggerConfig)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SlackLoggerConfig", _slackLoggerConfig == null ? null : _slackLoggerConfig.getMendixObject());
		Core.microflowCall("SlackLogger.ACT_SendTestMessage").withParams(params).execute(context);
	}
	public static boolean aSU_RegisterSlackLogger(IContext context, java.lang.String _configName)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ConfigName", _configName);
		return (java.lang.Boolean) Core.microflowCall("SlackLogger.ASU_RegisterSlackLogger").withParams(params).execute(context);
	}
	public static boolean bCO_SlackLoggerConfig(IContext context, slacklogger.proxies.SlackLoggerConfig _slackLoggerConfig)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SlackLoggerConfig", _slackLoggerConfig == null ? null : _slackLoggerConfig.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("SlackLogger.BCO_SlackLoggerConfig").withParams(params).execute(context);
	}
	public static void bSD_ShutdownSlackLoggers(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("SlackLogger.BSD_ShutdownSlackLoggers").withParams(params).execute(context);
	}
}
