// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package slacklogger.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the SlackLogger module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ReConfigRequestBuilder(
		slacklogger.proxies.SlackLoggerStatus _slackLoggerStatus
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SlackLogger.ACT_ReConfigRequest");
		builder = builder.withParam("SlackLoggerStatus", _slackLoggerStatus);
		return builder;
	}

	public static void aCT_ReConfigRequest(
		IContext context,
		slacklogger.proxies.SlackLoggerStatus _slackLoggerStatus
	)
	{
		aCT_ReConfigRequestBuilder(
				_slackLoggerStatus
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_SendTestMessageBuilder(
		slacklogger.proxies.SlackLoggerConfig _slackLoggerConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SlackLogger.ACT_SendTestMessage");
		builder = builder.withParam("SlackLoggerConfig", _slackLoggerConfig);
		return builder;
	}

	public static void aCT_SendTestMessage(
		IContext context,
		slacklogger.proxies.SlackLoggerConfig _slackLoggerConfig
	)
	{
		aCT_SendTestMessageBuilder(
				_slackLoggerConfig
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestRegexsBuilder(
		slacklogger.proxies.RegexpMatchTester _regexpMatchTester,
		slacklogger.proxies.SlackLoggerConfig _slackLoggerConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SlackLogger.ACT_TestRegexs");
		builder = builder.withParam("RegexpMatchTester", _regexpMatchTester);
		builder = builder.withParam("SlackLoggerConfig", _slackLoggerConfig);
		return builder;
	}

	public static void aCT_TestRegexs(
		IContext context,
		slacklogger.proxies.RegexpMatchTester _regexpMatchTester,
		slacklogger.proxies.SlackLoggerConfig _slackLoggerConfig
	)
	{
		aCT_TestRegexsBuilder(
				_regexpMatchTester,
				_slackLoggerConfig
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSU_RegisterSlackLoggerBuilder(
		java.lang.String _configName
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SlackLogger.ASU_RegisterSlackLogger");
		builder = builder.withParam("ConfigName", _configName);
		return builder;
	}

	public static boolean aSU_RegisterSlackLogger(
		IContext context,
		java.lang.String _configName
	)
	{
		Object result = aSU_RegisterSlackLoggerBuilder(
				_configName
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder bCO_SlackLoggerConfigBuilder(
		slacklogger.proxies.SlackLoggerConfig _slackLoggerConfig
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SlackLogger.BCO_SlackLoggerConfig");
		builder = builder.withParam("SlackLoggerConfig", _slackLoggerConfig);
		return builder;
	}

	public static boolean bCO_SlackLoggerConfig(
		IContext context,
		slacklogger.proxies.SlackLoggerConfig _slackLoggerConfig
	)
	{
		Object result = bCO_SlackLoggerConfigBuilder(
				_slackLoggerConfig
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder bSD_ShutdownSlackLoggersBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SlackLogger.BSD_ShutdownSlackLoggers");
		return builder;
	}

	public static void bSD_ShutdownSlackLoggers(IContext context)
	{
		bSD_ShutdownSlackLoggersBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_RegexpMatchTesterBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("SlackLogger.DS_RegexpMatchTester");
		return builder;
	}

	public static slacklogger.proxies.RegexpMatchTester dS_RegexpMatchTester(IContext context)
	{
		Object result = dS_RegexpMatchTesterBuilder().execute(context);
		return result == null ? null : slacklogger.proxies.RegexpMatchTester.initialize(context, (IMendixObject) result);
	}
}
