// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("b96399e4-caf6-4f86-abcc-a0382989bad5"),
	startsWith("ea723fba-8092-4b58-a1ec-2503d34f6659"),
	endsWith("2b5ed1f8-5a32-4658-ac7b-900041e379e2"),
	between("aaa00ee5-1159-42fa-9616-3373fae03e7b"),
	greater("7a99bf36-c52a-451e-b3e5-079148f55880"),
	greaterEqual("8594f267-5ddc-4e3a-b4c9-0db27b3847d9"),
	equal("7d9a3f3e-0e19-4bb8-819d-f922281242ec"),
	notEqual("c1fb534b-15a6-43da-9e27-2843fb6f1655"),
	smaller("d13fa38f-e1ef-4f7f-a893-8b7fd9055e20"),
	smallerEqual("7169d5ca-04bc-4bf9-8b3e-d52c9b04e6b4"),
	empty("1907b4d3-7600-4ebf-8716-16ab89c91dbc"),
	notEmpty("04851d5a-7b44-48b2-b68c-c21256415015");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
