// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package slacklogger.proxies;

public enum LogLevels
{
	TRACE("68930b2d-e0fc-452f-8f92-bf8314810914"),
	DEBUG("1f94be09-36b1-479a-9a38-52556ff20bac"),
	INFO("758487f6-a7e0-4448-974f-7c052ee01f4f"),
	WARNING("67415ad9-5b34-4fe8-8540-d4b9005514d6"),
	ERROR("da094294-3261-44d4-a597-719dcd669913"),
	CRITICAL("a33a48a0-02c5-4ebb-8bf3-38bde050cef6");

	private final java.lang.String i18nCaptionKey;
	
	private LogLevels(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
