// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package slacklogger.proxies;

public class SlackLoggerStatus
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject slackLoggerStatusMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SlackLogger.SlackLoggerStatus";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IpAddress("IpAddress"),
		ConfigName("ConfigName"),
		ConfigVersionNum("ConfigVersionNum"),
		LastProcessTime("LastProcessTime"),
		LastProcessResult("LastProcessResult"),
		LastErrorTime("LastErrorTime"),
		LastErrorInfo("LastErrorInfo"),
		OverflowedCount("OverflowedCount"),
		ExcludedCount("ExcludedCount"),
		ReconfigRequest("ReconfigRequest");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SlackLoggerStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SlackLogger.SlackLoggerStatus"));
	}

	protected SlackLoggerStatus(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject slackLoggerStatusMendixObject)
	{
		if (slackLoggerStatusMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SlackLogger.SlackLoggerStatus", slackLoggerStatusMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SlackLogger.SlackLoggerStatus");

		this.slackLoggerStatusMendixObject = slackLoggerStatusMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SlackLoggerStatus.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static slacklogger.proxies.SlackLoggerStatus initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return slacklogger.proxies.SlackLoggerStatus.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static slacklogger.proxies.SlackLoggerStatus initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new slacklogger.proxies.SlackLoggerStatus(context, mendixObject);
	}

	public static slacklogger.proxies.SlackLoggerStatus load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return slacklogger.proxies.SlackLoggerStatus.initialize(context, mendixObject);
	}

	public static java.util.List<slacklogger.proxies.SlackLoggerStatus> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<slacklogger.proxies.SlackLoggerStatus> result = new java.util.ArrayList<slacklogger.proxies.SlackLoggerStatus>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SlackLogger.SlackLoggerStatus" + xpathConstraint))
			result.add(slacklogger.proxies.SlackLoggerStatus.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of IpAddress
	 */
	public final java.lang.String getIpAddress()
	{
		return getIpAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of IpAddress
	 */
	public final java.lang.String getIpAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IpAddress.toString());
	}

	/**
	 * Set value of IpAddress
	 * @param ipaddress
	 */
	public final void setIpAddress(java.lang.String ipaddress)
	{
		setIpAddress(getContext(), ipaddress);
	}

	/**
	 * Set value of IpAddress
	 * @param context
	 * @param ipaddress
	 */
	public final void setIpAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ipaddress)
	{
		getMendixObject().setValue(context, MemberNames.IpAddress.toString(), ipaddress);
	}

	/**
	 * @return value of ConfigName
	 */
	public final java.lang.String getConfigName()
	{
		return getConfigName(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfigName
	 */
	public final java.lang.String getConfigName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ConfigName.toString());
	}

	/**
	 * Set value of ConfigName
	 * @param configname
	 */
	public final void setConfigName(java.lang.String configname)
	{
		setConfigName(getContext(), configname);
	}

	/**
	 * Set value of ConfigName
	 * @param context
	 * @param configname
	 */
	public final void setConfigName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String configname)
	{
		getMendixObject().setValue(context, MemberNames.ConfigName.toString(), configname);
	}

	/**
	 * @return value of ConfigVersionNum
	 */
	public final java.lang.Long getConfigVersionNum()
	{
		return getConfigVersionNum(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfigVersionNum
	 */
	public final java.lang.Long getConfigVersionNum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ConfigVersionNum.toString());
	}

	/**
	 * Set value of ConfigVersionNum
	 * @param configversionnum
	 */
	public final void setConfigVersionNum(java.lang.Long configversionnum)
	{
		setConfigVersionNum(getContext(), configversionnum);
	}

	/**
	 * Set value of ConfigVersionNum
	 * @param context
	 * @param configversionnum
	 */
	public final void setConfigVersionNum(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long configversionnum)
	{
		getMendixObject().setValue(context, MemberNames.ConfigVersionNum.toString(), configversionnum);
	}

	/**
	 * @return value of LastProcessTime
	 */
	public final java.util.Date getLastProcessTime()
	{
		return getLastProcessTime(getContext());
	}

	/**
	 * @param context
	 * @return value of LastProcessTime
	 */
	public final java.util.Date getLastProcessTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastProcessTime.toString());
	}

	/**
	 * Set value of LastProcessTime
	 * @param lastprocesstime
	 */
	public final void setLastProcessTime(java.util.Date lastprocesstime)
	{
		setLastProcessTime(getContext(), lastprocesstime);
	}

	/**
	 * Set value of LastProcessTime
	 * @param context
	 * @param lastprocesstime
	 */
	public final void setLastProcessTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastprocesstime)
	{
		getMendixObject().setValue(context, MemberNames.LastProcessTime.toString(), lastprocesstime);
	}

	/**
	 * @return value of LastProcessResult
	 */
	public final java.lang.String getLastProcessResult()
	{
		return getLastProcessResult(getContext());
	}

	/**
	 * @param context
	 * @return value of LastProcessResult
	 */
	public final java.lang.String getLastProcessResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastProcessResult.toString());
	}

	/**
	 * Set value of LastProcessResult
	 * @param lastprocessresult
	 */
	public final void setLastProcessResult(java.lang.String lastprocessresult)
	{
		setLastProcessResult(getContext(), lastprocessresult);
	}

	/**
	 * Set value of LastProcessResult
	 * @param context
	 * @param lastprocessresult
	 */
	public final void setLastProcessResult(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastprocessresult)
	{
		getMendixObject().setValue(context, MemberNames.LastProcessResult.toString(), lastprocessresult);
	}

	/**
	 * @return value of LastErrorTime
	 */
	public final java.util.Date getLastErrorTime()
	{
		return getLastErrorTime(getContext());
	}

	/**
	 * @param context
	 * @return value of LastErrorTime
	 */
	public final java.util.Date getLastErrorTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastErrorTime.toString());
	}

	/**
	 * Set value of LastErrorTime
	 * @param lasterrortime
	 */
	public final void setLastErrorTime(java.util.Date lasterrortime)
	{
		setLastErrorTime(getContext(), lasterrortime);
	}

	/**
	 * Set value of LastErrorTime
	 * @param context
	 * @param lasterrortime
	 */
	public final void setLastErrorTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lasterrortime)
	{
		getMendixObject().setValue(context, MemberNames.LastErrorTime.toString(), lasterrortime);
	}

	/**
	 * @return value of LastErrorInfo
	 */
	public final java.lang.String getLastErrorInfo()
	{
		return getLastErrorInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of LastErrorInfo
	 */
	public final java.lang.String getLastErrorInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastErrorInfo.toString());
	}

	/**
	 * Set value of LastErrorInfo
	 * @param lasterrorinfo
	 */
	public final void setLastErrorInfo(java.lang.String lasterrorinfo)
	{
		setLastErrorInfo(getContext(), lasterrorinfo);
	}

	/**
	 * Set value of LastErrorInfo
	 * @param context
	 * @param lasterrorinfo
	 */
	public final void setLastErrorInfo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lasterrorinfo)
	{
		getMendixObject().setValue(context, MemberNames.LastErrorInfo.toString(), lasterrorinfo);
	}

	/**
	 * @return value of OverflowedCount
	 */
	public final java.lang.Long getOverflowedCount()
	{
		return getOverflowedCount(getContext());
	}

	/**
	 * @param context
	 * @return value of OverflowedCount
	 */
	public final java.lang.Long getOverflowedCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.OverflowedCount.toString());
	}

	/**
	 * Set value of OverflowedCount
	 * @param overflowedcount
	 */
	public final void setOverflowedCount(java.lang.Long overflowedcount)
	{
		setOverflowedCount(getContext(), overflowedcount);
	}

	/**
	 * Set value of OverflowedCount
	 * @param context
	 * @param overflowedcount
	 */
	public final void setOverflowedCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long overflowedcount)
	{
		getMendixObject().setValue(context, MemberNames.OverflowedCount.toString(), overflowedcount);
	}

	/**
	 * @return value of ExcludedCount
	 */
	public final java.lang.Long getExcludedCount()
	{
		return getExcludedCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ExcludedCount
	 */
	public final java.lang.Long getExcludedCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ExcludedCount.toString());
	}

	/**
	 * Set value of ExcludedCount
	 * @param excludedcount
	 */
	public final void setExcludedCount(java.lang.Long excludedcount)
	{
		setExcludedCount(getContext(), excludedcount);
	}

	/**
	 * Set value of ExcludedCount
	 * @param context
	 * @param excludedcount
	 */
	public final void setExcludedCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long excludedcount)
	{
		getMendixObject().setValue(context, MemberNames.ExcludedCount.toString(), excludedcount);
	}

	/**
	 * @return value of ReconfigRequest
	 */
	public final java.lang.Boolean getReconfigRequest()
	{
		return getReconfigRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of ReconfigRequest
	 */
	public final java.lang.Boolean getReconfigRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ReconfigRequest.toString());
	}

	/**
	 * Set value of ReconfigRequest
	 * @param reconfigrequest
	 */
	public final void setReconfigRequest(java.lang.Boolean reconfigrequest)
	{
		setReconfigRequest(getContext(), reconfigrequest);
	}

	/**
	 * Set value of ReconfigRequest
	 * @param context
	 * @param reconfigrequest
	 */
	public final void setReconfigRequest(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean reconfigrequest)
	{
		getMendixObject().setValue(context, MemberNames.ReconfigRequest.toString(), reconfigrequest);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return slackLoggerStatusMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final slacklogger.proxies.SlackLoggerStatus that = (slacklogger.proxies.SlackLoggerStatus) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SlackLogger.SlackLoggerStatus";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
