// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package home.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Home module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_GetXASIdBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Home.ACT_GetXASId");
		return builder;
	}

	public static void aCT_GetXASId(IContext context)
	{
		aCT_GetXASIdBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_SendMessageToSlackTestBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Home.ACT_SendMessageToSlackTest");
		return builder;
	}

	public static void aCT_SendMessageToSlackTest(IContext context)
	{
		aCT_SendMessageToSlackTestBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_WriteErrorLogBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Home.ACT_WriteErrorLog");
		return builder;
	}

	public static void aCT_WriteErrorLog(IContext context)
	{
		aCT_WriteErrorLogBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_WriteInfoLogBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Home.ACT_WriteInfoLog");
		return builder;
	}

	public static void aCT_WriteInfoLog(IContext context)
	{
		aCT_WriteInfoLogBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSU_TestAppBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Home.ASU_TestApp");
		return builder;
	}

	public static boolean aSU_TestApp(IContext context)
	{
		Object result = aSU_TestAppBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder bSD_TestAppBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Home.BSD_TestApp");
		return builder;
	}

	public static void bSD_TestApp(IContext context)
	{
		bSD_TestAppBuilder().execute(context);
	}
}
