// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package home.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the Home module
	public static void aCT_GetXASId(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Home.ACT_GetXASId").withParams(params).execute(context);
	}
	public static void aCT_SendMessageToSlackTest(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Home.ACT_SendMessageToSlackTest").withParams(params).execute(context);
	}
	public static void aCT_WriteErrorLog(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Home.ACT_WriteErrorLog").withParams(params).execute(context);
	}
	public static void aCT_WriteInfoLog(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Home.ACT_WriteInfoLog").withParams(params).execute(context);
	}
	public static boolean aSU_TestApp(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("Home.ASU_TestApp").withParams(params).execute(context);
	}
	public static void bSD_TestApp(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Home.BSD_TestApp").withParams(params).execute(context);
	}
}